### ISSUE TITLE
On MacOS, even ``make clean html`` seems to invoke inkscape

### ISSUE THREAD

**Issue by jfbu** [missinglinkelectronics/sphinxcontrib-svg2pdfconverter#1]
I have Inkscape installed 0.92.2 installed on my Mac as a Mac application. 

The extension 👍 works fine with PATH extended to contain ``/Applications/Inkscape.app/Contents/Resources/bin``.

When using ``make clean html`` on a simple project with

```
extensions = [
    'sphinxcontrib.inkscapeconverter',
]
```

there seems to be some Inkscape related activity because an XQuartz session is launched, which induces a small delay. But, the HTML ouput will use `foo.svg` as is, so I am wondering if this sllght delay could be avoided. This is minor because once XQuartz got launched and remains open, no noticeable delay seems to arise from subsequent ``make clean html``.

**Comment by jfbu** [comment]
Using 

```
inkscape_converter_args = ['--without-gui', '--export-area-drawing']
```

does not modify my issue. I suspect thus a feature of Inkscape installed on MacOS as a Mac Application, perhaps some more knowledgeable person will give the needed info.

**Comment by sephalon** [comment]
Inkscape is invoked in the method `is_available` as well, even if the conversion rule does not apply to the target. Could you please change line 38 in `inkscapeconverter.py` from

```python
    args = [self.config.inkscape_converter_bin, '--version']
```

to

```python
    args = [self.config.inkscape_converter_bin, '--without-gui', '--version']
```

and check if that fixes the issue?

**Comment by jfbu** [comment]
I tried but it does not help. Actually from command line

```
$ /Applications/Inkscape.app/Contents/Resources/bin/inkscape -z --help
```

(where  ``-z`` is synonymous with ``--without-gui``) displays the help in the Terminal, but the XQuartz is launched anyway. Same with `--version` in place of `--help`.

I am afraid this is a feature of Inkscape packaging for MacOS and in view of https://inkscape.org/en/ it seems MacOS support is somewhat lagging behind over there. For example there is no pre-built binaries offered currently  at https://inkscape.org/en/release/0.92.3/platforms/

I could try out a MacPorts install to see if that changes something compared to a binary download from inkscape.org.

**Comment by sephalon** [comment]
I'll close this for now as it seems like there's nothing that can be done from the extensions point of view.

**Comment by sephalon** [comment]
I just read the news that [Inkscape 1.0 beta1 is out](https://inkscape.org/news/2019/09/08/inkscape-10-beta1-available-testing/), which is [a native macOS application now and does not require XQuartz anymore](http://wiki.inkscape.org/wiki/index.php/Release_notes/1.0#Mac_Application). Maybe this solves your problem?

**Comment by jfbu** [comment]
I am definitely eager to try it out but it seems they support macOS : 10.10-10.15. And I am still on 10.9.5 ! (and sticking with it).
