### ISSUE TITLE
ENOENT missing in Sphinx 4.0 (= master branch)

### ISSUE THREAD

**Issue by mgeier** [missinglinkelectronics/sphinxcontrib-svg2pdfconverter#11]
When using the Sphinx `master` branch (which will eventually become Sphinx 4.0), I get this error:

```
Extension error:
Could not import extension sphinxcontrib.rsvgconverter (exception: cannot import name 'ENOENT' from 'sphinx.util.osutil'
```

This constant was marked for removal in in https://github.com/sphinx-doc/sphinx/pull/5797 and removed in https://github.com/sphinx-doc/sphinx/pull/7416.

According to https://www.sphinx-doc.org/en/master/extdev/deprecated.html, the replacement is `errno.ENOENT` or `FileNotFoundError`.

Same problem with `EPIPE` and `EINVAL`.

**Comment by sephalon** [comment]
Fixed in https://github.com/missinglinkelectronics/sphinxcontrib-svg2pdfconverter/commit/252a0b0fa097686dae84e8d7c39f901dc010a531. Thank you for making me aware of this issue!
