### ISSUE TITLE
Sphinx < 1.8 not supported

### ISSUE THREAD

**Issue by mgeier** [missinglinkelectronics/sphinxcontrib-svg2pdfconverter#2]
`setup.py` claims to support Sphinx 1.6:

https://github.com/missinglinkelectronics/sphinxcontrib-svg2pdfconverter/blob/b57700a1efdf30b894ef38965ae91dba99ef8736/setup.py#L10

But this is used:

https://github.com/missinglinkelectronics/sphinxcontrib-svg2pdfconverter/blob/b57700a1efdf30b894ef38965ae91dba99ef8736/sphinxcontrib/rsvgconverter.py#L16

Which was introduced in Sphinx 1.8: https://github.com/sphinx-doc/sphinx/pull/4674

**Comment by sephalon** [comment]
Sphinx 1.6 is actually supported, but starting only from 1.6.3, [when a dummy wrapper for `__()` was introduced](https://github.com/sphinx-doc/sphinx/commit/41bb5f7fd26a5d4e8c24812a47aa50f46e88eb70#diff-be9779a1b6bbb4250de676dbf32a201eR245). I will fix the version requirement.

**Comment by mgeier** [comment]
Thanks for the info.
I've removed my own dummy wrapper and updated my own requirements to Sphinx 1.6.3 (https://github.com/spatialaudio/nbsphinx/pull/322) and now my tests pass!

**Comment by sephalon** [comment]
Release v1.0.1 including this fix is now out; so you might want to update your dependencies.
