### ISSUE TITLE
broken link on pypi

### ISSUE THREAD

**Issue by LocutusOfBorg** [missinglinkelectronics/sphinxcontrib-svg2pdfconverter#3]
HOMEPAGE here:  https://pypi.org/project/sphinxcontrib-svg2pdfconverter/
Is listed as github.org and not github.com

Not sure where I have to report this...

**Comment by sephalon** [comment]
Already fixed in e8b28a72bb1f448ae3a713b8533ab9a6bd717e49, but unfortunately there hasn't been a release that includes this commit yet. I'll prepare a new release as soon as #2 is closed.

**Comment by sephalon** [comment]
> nice! I'm going to upload in Debian this package soon :D

Great! Release v1.0.1 is now out; let me know if there are any further issues in the packaging process.

**Comment by LocutusOfBorg** [comment]
I already uploaded it in both Debian and Ubuntu, they will be part of next stable!
thanks a lot for your effort!

**Comment by LocutusOfBorg** [comment]
you can see them here
https://tracker.debian.org/pkg/sphinxcontrib-svg2pdfconverter
https://launchpad.net/ubuntu/+source/sphinxcontrib-svg2pdfconverter
