### ISSUE TITLE
The differences between two sphinxcontrib-svg2pdfconverter repos on github.

### ISSUE THREAD

**Issue by hongyi-zhao** [missinglinkelectronics/sphinxcontrib-svg2pdfconverter#6]
Hi,

I noted there are two repos for the sphinxcontrib-svg2pdfconverter:

https://github.com/missinglinkelectronics/sphinxcontrib-svg2pdfconverter
https://github.com/sephalon/sphinxcontrib-svg2pdfconverter

It seems they are the same and they are not cloned from each other.  If they precisely same, why preserver two repos for them on github?

Regards

**Comment by sephalon** [comment]
Thanks for making me aware of this; I hosted this repo on my personal account before it became part of my employer's account. Therefore,

https://github.com/missinglinkelectronics/sphinxcontrib-svg2pdfconverter

is the correct upstream repo. I will delete

https://github.com/sephalon/sphinxcontrib-svg2pdfconverter

and recreate by cloning from upstream again so it is clearly marked as a clone.
