### ISSUE TITLE
After pip install --upgrade your package, I still have the old behavior (--export-pdf)

### ISSUE THREAD

**Issue by davbeek** [missinglinkelectronics/sphinxcontrib-svg2pdfconverter#9]
I use Inkscape 1.0. I saw in your code that you have updated the export functionality by testing the Inkscape version number if it begins with 1.

However, after updating (pip install --upgrade sphinxcontrib-svg2pdfconverter), I see in inkscapeconverter.py that it is still the old functionality (no test for Inkscape version), but pip reports the 1.0.1 version of your package. Sphinx still gives an error: unknown option --export-pdf.

I am doing something wrong?

**Comment by QuLogic** [comment]
I don't think that change has been released, and it would be nice if it were.

**Comment by sephalon** [comment]
Yes, I planned to accumulate another change before doing the release. However, v1.1.0 is now out. Sorry about the confusion!
